# Generated by Django 5.1.3 on 2026-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='is_embedded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='vector',
            field=models.TextField(blank=True, default='', help_text='JSON-encoded float vector'),
        ),
    ]
