# Generated by Django 5.1.3 on 2026-05-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField(blank=True, default='')),
                ('num_media', models.PositiveIntegerField(default=0)),
                ('reply', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='core.whatsappuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
